name: CI Pipeline

on:
  - push

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          go test ./... -coverprofile=coverage/coverage.out -covermode=atomic

      - name: Upload coverage to artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage/coverage.out

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=gabriel-rp_go-broker
            -Dsonar.organization=gabriel-rp
            -Dsonar.go.coverage.reportPaths=coverage/coverage.out
